config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'blog', to: 'pages#blog'
  get 'contact', to: 'pages#contact'
  get 'estimate', to: 'pages#estimate'
  get 'new', to: 'pages#new'
  resources :propertys
  resources :locations
  resources :lots
  resources :actualitys
  resources :nouvelles
end

app/models/actuality.rb
# frozen_string_literal: true

class Actuality < ApplicationRecord
  validates :name, presence: true
  validates :texte, presence: true
  validates :date, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  scope :min_price, ->(min) { where('cast(price as text) > ?', min) }
  scope :max_price, ->(max) { where('cast(price as text) < ?', max) }
  scope :min_room, ->(min) { where('cast(room as text) > ?', min) }
  validates :name, presence: true
  validates :room, presence: true
  validates :metre, presence: true
  validates :city, presence: true
  validates :price, presence: true
  validates :ref, presence: true
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/lot.rb
# frozen_string_literal: true

class Lot < ApplicationRecord
  scope :min_price, ->(min) { where('cast(price as text) > ?', min) }
  scope :max_price, ->(max) { where('cast(price as text) < ?', max) }
  validates :name, presence: true
  validates :metre, presence: true
  validates :city, presence: true
  validates :price, presence: true
  validates :ref, presence: true
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/nouvelle.rb
# frozen_string_literal: true

class Nouvelle < ApplicationRecord
  validates :name, presence: true
  validates :texte, presence: true
  validates :date, presence: true
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  scope :min_price, ->(min) { where('cast(price as text) > ?', min) }
  scope :max_price, ->(max) { where('cast(price as text) < ?', max) }
  scope :min_room, ->(min) { where('cast(room as text) > ?', min) }
  validates :name, presence: true
  validates :room, presence: true
  validates :metre, presence: true
  validates :city, presence: true
  validates :price, presence: true
  validates :ref, presence: true
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/controllers/actualitys_controller.rb
# frozen_string_literal: true

class ActualitysController < ApplicationController
  def index
    @actualitys = Actuality.order(date: :desc)
  end

  def show
    @actuality = Actuality.find(params[:id])
  end
end
class Date
  def current
    ::Time.zone ? ::Time.zone.today : ::Date.today
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  def index
    grow = 1
    scope = 10 * grow
    if params[:city].present? && params[:price_min].present? || params[:price_max].present? && params[:room].present?
      results = Location.near(params[:city], scope).order(:distance).min_price(params[:price_min]).max_price(params[:price_max]).min_room(params[:room])
      while results.empty?
        grow += 2
        scope += 10 * grow
        results = Location.near(params[:city], scope, units: :km).order(:distance).limit(4)
      end
      @locations = results

    elsif params[:price_min].present? || params[:price_max].present?
      result = Location.min_price(params[:price_min]).max_price(params[:price_max])
      @locations = result

    elsif params[:city].present?
      results = Location.near(params[:city], scope).order(:distance)
      while results.empty?
        grow += 2
        scope += 10 * grow
        results = Location.near(params[:city], scope, units: :km).order(:distance).limit(4)
      end
      @locations = results

    elsif params[:room].present?
      @locations = Location.min_room(params[:room])

    else
      @locations = Location.all
    end

    # @markers = @locations.map do |property|
    #   {
    #     lat: property.latitude,
    #     lng: property.longitude
    #   }
    # end
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/lots_controller.rb
# frozen_string_literal: true

class LotsController < ApplicationController
  def index
    grow = 1
    scope = 10 * grow
    if params[:city].present? && params[:price_min].present? || params[:price_max].present?
      results = Lot.near(params[:city], scope).order(:distance).min_price(params[:price_min]).max_price(params[:price_max])
      while results.empty?
        grow += 2
        scope += 100 * grow
        results = Lot.near(params[:city], scope, units: :km).order(:distance).limit(4)
      end
      @lots = results

    elsif params[:price_min].present? || params[:price_max].present?
      result = Lot.min_price(params[:price_min]).max_price(params[:price_max])
      @lots = result

    elsif params[:city].present?
      results = Lot.near(params[:city], scope).order(:distance)
      while results.empty?
        grow += 2
        scope += 100 * grow
        results = Lot.near(params[:city], scope, units: :km).order(:distance).limit(4)
      end
      @lots = results
    else
      @lots = Lot.all
    end
  end

  def show
    @lot = Lot.find(params[:id])
  end
end
class String
  def in_groups_of(n, sep = ' ')
    chars.each_slice(n).map(&:join).join(sep)
  end
end

app/controllers/nouvelles_controller.rb
# frozen_string_literal: true

class NouvellesController < ApplicationController
  def index
    @nouvelles = Nouvelle.order(date: :desc)
  end

  def show
    @nouvelle = Nouvelle.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def blog; end

  def contact; end

  def estimate; end
end

app/controllers/propertys_controller.rb
# frozen_string_literal: true

class PropertysController < ApplicationController
  def index
    grow = 1
    scope = 10 * grow
    if params[:city].present? && params[:price_min].present? || params[:price_max].present? && params[:room].present?
      results = Property.near(params[:city], scope).order(:distance).min_price(params[:price_min]).max_price(params[:price_max]).min_room(params[:room])
      while results.empty?
        grow += 2
        scope += 10 * grow
        results = Property.near(params[:city], scope, units: :km).order(:distance).limit(4)
      end
      @propertys = results

    elsif params[:price_min].present? || params[:price_max].present?
      result = Property.min_price(params[:price_min]).max_price(params[:price_max])
      @propertys = result

    elsif params[:city].present?
      results = Property.near(params[:city], scope).order(:distance)
      while results.empty?
        grow += 2
        scope += 10 * grow
        results = Property.near(params[:city], scope, units: :km).order(:distance).limit(4)
      end
      @propertys = results

    elsif params[:room].present?
      @propertys = Property.min_room(params[:room])

    else
      @propertys = Property.all
    end
  end

  def show
    @property = Property.find(params[:id])
  end
end
class String
  def in_groups_of(n, sep = ' ')
    chars.each_slice(n).map(&:join).join(sep)
  end
end

app/helpers/actuality_helper.rb
# frozen_string_literal: true

module ActualityHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/helpers/lots_helper.rb
# frozen_string_literal: true

module LotsHelper
end

app/helpers/nouvelles_helper.rb
# frozen_string_literal: true

module NouvellesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/propertys_helper.rb
# frozen_string_literal: true

module PropertysHelper
end

app/views/actualitys/show.html.erb
<body id="blog">
  <h5 style="font-size: 2em;" id="back"><%= link_to  actualitys_path do %>
    <%= fa_icon "chevron-left" %> Retour
    <% end %>
  </h5>
  <div class="container" id="cadreactu">
    <%= image_tag "article.jpg", id: "imgactu"%>
    <h1> <%= @actuality.name %> <h1>
      <p id="texte"> <%= @actuality.texte %> </p>
      <p style="margin-left: 15px; font-size: 0.5em !important;"> <%= @actuality.date %></p>
    </div>
  </body>

app/views/locations/index.html.erb
<body id="sell">
<div class="container-fluid">
 <div id="Carousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-content">
     <div class="button-effect">
       <h3><%= link_to "Blog", actualitys_path, class: "effect effect-5"%>
        <%= link_to "Contact", contact_path, class: "effect effect-5" %></h3>
      </div>
      <h4>IMMO +</h4>
      <div class="search">
       <h2>Trouvez votre chez-vous </h2>
       <div id="searchstyle">
         <%= form_tag @propertys_path, method: :get do %>
         <%= text_field_tag :city, params[:city],
         class: "form-control", id: "city", placeholder: "Où voulez-vous vivre?"  %>
         <div class="row no-gutter">
          <div class="col-lg-6">
            <%= text_field_tag :price_min, params[:price_min],
            class: "form-control", id: "pricemin", placeholder: "Prix min"  %>
          </div>
          <div class="col-lg-6">
            <%= text_field_tag :price_max, params[:price_max],
            class: "form-control", id: "pricemax", placeholder: "Prix max"  %>
          </div>
        </div>
        <%= text_field_tag :room, params[:room],
        class: "form-control", id: "room", placeholder: "Nombre de pièces min"  %>
        <%= submit_tag "Search", class: "btn btn-primary", id: "searchbtn" %>
        <% end %>
      </div>
      </div>
      <ul class="list-inline tabs-underlined">
        <li>
          <%= link_to "Accueil", root_path,class: "tab-underlined", id: "acc"%>
       </li>
        <li>
         <%= link_to "Achat", propertys_path,class: "tab-underlined "%>
       </li>
       <li>
         <%= link_to "Location", locations_path, class: "tab-underlined active", id: "uder2"  %>
       </li>
       <li>
         <%= link_to "Terrain", lots_path, class: "tab-underlined"  %>
       </li>
       <li>
         <%= link_to "Estimation", estimate_path, class: "tab-underlined"%>
       </li>
     </ul>
   </div>
   <div class="item active">
    <%= image_tag "house_fond3.jpg", class: "d-block w-100", alt: "Carrousel slide 1", crop: :fill%>
  </div>
  <div class="item">
    <%= image_tag "house_snow.jpg", class: "d-block w-100", alt: "Carrousel slide 2", crop: :fill %>
  </div>
  <div class="item">
    <%= image_tag "housefd.jpg", class: "d-block w-100", alt: "Carrousel slide 3", crop: :fill%>
  </div>
  <div class="item">
    <%= image_tag "carrouselfond2.jpg", class: "d-block w-100", alt: "Carrousel slide 4", crop: :fill%>
  </div>
  <div class="item">
    <%= image_tag "carrouselfond3.jpg", class: "d-block w-100", alt: "Carrousel slide 5", crop: :fill%>
  </div>
</div>
</div>

<div class="row">
 <div class="cards">
  <% @locations.each do |locate| %>
  <%if locate == @locations.first%>
  <div class="card-product" id="cardlocate">
    <div class="image-container">
     <div class="ribbon-wrapper"><div class="ribbon">Exclusivité</div></div>

     <% if locate.name == "Maison" %>
     <%= image_tag "house_interior.jpg" %>
     <% else %>
     <%= image_tag "locate.jpg" %>
     <%end %>
     <div class="after">
      <h2> <%= "Type de bien: #{@locations.first.name}" %> </h2>
      <h2> <%= "Surface: #{@locations.first.metre} m²" %> </h2>
      <h2> <%= "Nombre de pièces: #{@locations.first.room} " %> </h2>
      <h2> <%= "Situé à #{@locations.first.city}" %> </h2>
      <h2> <%= "Prix: #{@locations.first.price.to_s.in_groups_of(3)} €" %> </h2>
      <h2> <%= "Reférence de l'annonce:  #{@locations.first.ref}" %></h2>
    </div>
  </div>
  <div class="card-product-infos">
    <h2><%= "#{@locations.first.name} de #{@locations.first.metre} m²"%> </h2>
    <p> <%= "Situé à #{@locations.first.city}" %> </p>
    <p id="prix"> <%= "Prix: #{@locations.first.price} €" %> </p>
    <h3><%= link_to   location_path(@locations.first) do %>
      Voir <%= image_tag "icons-plus.png", class: "imageplus"%>
      <% end %>
    </h3>
  </div>
</div>
<% end %>

<div class="card-product" id="cardlocate">
  <div class="image-container">
    <% if locate.name == "Maison" %>
    <%= image_tag "house_interior.jpg" %>
    <% else %>
    <%= image_tag "locate.jpg" %>
    <%end %>

    <div class="after">
      <h2> <%= "Type de bien: #{locate.name}" %> </h2>
      <h2> <%= "Surface: #{locate.metre} m²" %> </h2>
      <h2> <%= " Nombre de pièces: #{locate.room} " %> </h2>
      <h2> <%= "Situé à #{locate.city}" %> </h2>
      <h2> <%= "Prix: #{locate.price} €" %> </h2>
      <h2> <%= "Reférence de l'annonce:  #{locate.ref}" %></h2>
    </div>
  </div>
  <div class="card-product-infos">
    <h2><%= "#{locate.name} de #{locate.metre} m²" %></h2>
    <p> <%= "Situé à #{locate.city}" %> </p>
    <p id="prix"> <%= "Prix: #{locate.price} €" %> </p>
    <h3><%= link_to   location_path(locate) do %>
      Voir <%= image_tag "icons-plus.png", class: "imageplus"%>
      <% end %>
    </h3>
  </div>
</div>
<% end %>

</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({
      interval: 4000
    })
  });
</script>
</div>
</div>

</body>

app/views/lots/index.html.erb
<body id="sell">
<div class="container-fluid">
 <div id="Carousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-content">
     <div class="button-effect">
       <h3><%= link_to "Blog", actualitys_path, class: "effect effect-5"%>
        <%= link_to "Contact", contact_path, class: "effect effect-5" %></h3>
      </div>
      <h4>IMMO +</h4>
      <div class="search">
       <h2>Trouvez votre chez-vous </h2>
       <div id="searchstyle">
         <%= form_tag @propertys_path, method: :get do %>
         <%= text_field_tag :city, params[:city],
         class: "form-control", id: "city", placeholder: "Où voulez-vous vivre?"  %>
         <div class="row no-gutter">
          <div class="col-lg-6">
            <%= text_field_tag :price_min, params[:price_min],
            class: "form-control", id: "pricemin", placeholder: "Prix min"  %>
          </div>
          <div class="col-lg-6">
            <%= text_field_tag :price_max, params[:price_max],
            class: "form-control", id: "pricemax", placeholder: "Prix max"  %>
          </div>
        </div>
        <%= submit_tag "Search", class: "btn btn-primary", id: "searchbtn" %>
        <% end %>
      </div>
    </div>
    <ul class="list-inline tabs-underlined">
      <li>
        <%= link_to "Accueil", root_path,class: "tab-underlined", id: "acc"%>
      </li>
      <li>
       <%= link_to "Achat", propertys_path,class: "tab-underlined "%>
     </li>
     <li>
       <%= link_to "Location", locations_path, class: "tab-underlined"  %>
     </li>
     <li>
      <%= link_to "Terrain", lots_path, class: "tab-underlined active",id: "uder3"   %>
    </li>
    <li>
     <%= link_to "Estimation", estimate_path, class: "tab-underlined"%>
   </li>
 </ul>
</div>
<div class="item active">
  <%= image_tag "house_fond3.jpg", class: "d-block w-100", alt: "Carrousel slide 1", crop: :fill%>
</div>
<div class="item">
  <%= image_tag "house_snow.jpg", class: "d-block w-100", alt: "Carrousel slide 2", crop: :fill %>
</div>
<div class="item">
  <%= image_tag "housefd.jpg", class: "d-block w-100", alt: "Carrousel slide 3", crop: :fill%>
</div>
<div class="item">
  <%= image_tag "carrouselfond2.jpg", class: "d-block w-100", alt: "Carrousel slide 4", crop: :fill%>
</div>
<div class="item">
  <%= image_tag "carrouselfond3.jpg", class: "d-block w-100", alt: "Carrousel slide 5", crop: :fill%>
</div>
</div>

<div class="row">
 <div class="cards">
  <% @lots.each do |l| %>
  <%if l == @lots.first%>
  <div class="card-product" id="cardlot">
   <div class="image-container">
    <div class="ribbon-wrapper"><div class="ribbon">Exclusivité</div></div>
    <%= image_tag "lot.jpg" %>
    <div class="after">
      <h2> <%= "Type de bien: #{l.name}" %> </h2>
      <h2> <%= "Surface: #{l.metre} m²" %> </h2>
      <h2> <%= "Situé à #{l.city}" %> </h2>
      <h2> <%= "Prix: #{l.price.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ")} €" %> </h2>
      <h2> <%= "Reférence de l'annonce:  #{l.ref}" %>
      </div>
    </div>
    <div class="card-product-infos">
      <h2><%="#{l.name} de #{l.metre} m²" %></h2>
      <p> <%= "Situé à #{l.city}" %> </p>
      <p id="prix"> <%= "Prix: #{l.price.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ")} €" %> </p>
      <h3><%= link_to  lot_path(l) do %>
        Voir <%= image_tag "icons-plus.png", class: "imageplus"%>
        <% end %>
      </div>
    </div>
    <% else %>
    <div class="card-product" id="cardlot">
     <div class="image-container">
      <%= image_tag "lot.jpg" %>
      <div class="after">
        <h2> <%= "Type de bien: #{l.name}" %> </h2>
        <h2> <%= "Surface: #{l.metre} m²" %> </h2>
        <h2> <%= "Situé à #{l.city}" %> </h2>
        <h2> <%= "Prix: #{l.price.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ")} €" %> </h2>
        <h2> <%= "Reférence de l'annonce:  #{l.ref}" %>
        </div>
      </div>
      <div class="card-product-infos">
        <h2><%="#{l.name} de #{l.metre} m²" %></h2>
        <p> <%= "Situé à #{l.city}" %> </p>
        <p id="prix"> <%= "Prix: #{l.price.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ")} €" %> </p>
        <h3><%= link_to  lot_path(l) do %>
          Voir <%= image_tag "icons-plus.png", class: "imageplus"%>
          <% end %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <script type="text/javascript">
      $(document).ready(function() {
        $('.carousel').carousel({
          interval: 4000
        })
      });
    </script>
  </div>
</div>

</div>
</div>
</body>

app/views/pages/blog.html.erb
 <div class="container-fluid">
 <div class="banner">
     <div class="container">
         <h3><strong><%= link_to "Blog", blog_path %></strong> <strong><%= link_to "Contact", contact_path %></strong></h3>
        <h1> <strong><%= link_to "Actualité", actualitys_path %></strong>  Nouveauté </h1>
     </div>
</div>
</div>

<div class="container-fluid">
   <div id="Carousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-content">
        <h3><strong><%= link_to "Blog", actualitys_path %></strong> <strong><%= link_to "Contact", contact_path %></strong></h3>

        <h4>IMMO +</h4>
         <div class="estimate">
        <h2>Vous ne vous sentez plus chez vous ?</h2>
        <p id="punch">laissez-nous vendre pour vous !<p>
        </div>

          <div class="button-effect">
            <h1>
             <%= link_to "Achat", propertys_path,class: "effect effect-5" %>
             <%= link_to "Location", locations_path, class: "effect effect-5" %>
             <%= link_to "Terrain", lots_path, class: "effect effect-5"%>
             <%= link_to "Estimation", estimate_path, class: "effect effect-5", id: "linkeffect"%></h1>
           </div>
         </div>
         <div class="item active">
           <%= image_tag "article.jpg", class: "d-block w-100", alt: "Carrousel slide 1", crop: :fill%>
         </div>
         <div class="item">
          <%= image_tag "house_snow.jpg", class: "d-block w-100", alt: "Carrousel slide 2", crop: :fill%>
        </div>
        <div class="item">
          <%= image_tag "house_snow.jpg", class: "d-block w-100", alt: "Carrousel slide 3", crop: :fill %>
        </div>

      </div>
    </div>

app/views/pages/estimate.html.erb
<body id="estimate-contact">
  <div class="container-fluid">
   <div id="Carousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-content">
       <div class="button-effect">
         <h3><%= link_to "Blog", actualitys_path, class: "effect effect-5"%>
          <%= link_to "Contact", contact_path, class: "effect effect-5" %></h3>
        </div>
        <h4>IMMO +</h4>
        <div class="estimate">
          <h2>Vous ne vous sentez plus chez vous ?</h2>
          <p id="punch">laissez-nous vendre pour vous !<p>
          </div>
          <ul class="list-inline tabs-underlined">
            <li>
              <%= link_to "Accueil", root_path,class: "tab-underlined", id: "acc"%>
            </li>
            <li>
             <%= link_to "Achat", propertys_path,class: "tab-underlined "%>
           </li>
           <li>
             <%= link_to "Location", locations_path, class: "tab-underlined"  %>
           </li>
           <li>
             <%= link_to "Terrain", lots_path, class: "tab-underlined"  %>
           </li>
           <li>
             <%= link_to "Estimation", estimate_path, class: "tab-underlined active", id: "uder4"%>
           </li>
         </ul>
       </div>
       <div class="item active">
        <%= image_tag "house_fond3.jpg", class: "d-block w-100", alt: "Carrousel slide 1", crop: :fill%>
      </div>
      <div class="item">
        <%= image_tag "house_snow.jpg", class: "d-block w-100", alt: "Carrousel slide 2", crop: :fill %>
      </div>
      <div class="item">
        <%= image_tag "housefd.jpg", class: "d-block w-100", alt: "Carrousel slide 3", crop: :fill%>
      </div>
      <div class="item">
        <%= image_tag "carrouselfond2.jpg", class: "d-block w-100", alt: "Carrousel slide 4", crop: :fill%>
      </div>
      <div class="item">
        <%= image_tag "carrouselfond3.jpg", class: "d-block w-100", alt: "Carrousel slide 5", crop: :fill%>
      </div>
    </div>
  </div>

  <div class="color">
    <form class="form" id="form-estimate">

      <h2 id="h2-estimate">Estimation de votre bien</h2>
      <p type="Sélectionnez votre type de bien:"></p>
      <div class="select">
        <select>
          <option value="0">Sélectionnez</option>
          <option value="1">Maison</option>
          <option value="2">Appartement</option>
          <option value="3">Terrain</option>
        </select>
      </div>
      <p type="Adresse:"><input placeholder="123 boulevard jean jaurès"></input></p>
      <p type="Code postal:"><input placeholder="13000"></input></p>
      <p type="Ville:"><input placeholder="Marseille"></input></p>
      <p type="Nom:"><input placeholder="Votre nom"></input></p>
      <p type="Email:"><input placeholder="immo+@mail.com"></input></p>
      <button id="bttn" >Envoyez votre demande</button>
      <div id="bar-estimate">
        <h6>07.23.12.25.39</h6>
        <h6> immo+@mail.com </h6>
        <h6>Agence située à marseille </h6>
      </div>
    </form>
    <script type="text/javascript">
      $(document).ready(function() {
        $('.carousel').carousel({
          interval: 4000
        })
      });
    </script>
  </div>
</div>
</body>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small mdb-color lighten-3 pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mb-4">À propos de nous</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit amet numquam iure provident voluptate
          esse
        quasi, veritatis totam voluptas nostrum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit amet numquam iure provident voluptate
          esse
        quasi, veritatis totam voluptas nostrum.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mb-4">Liens</h5>

        <ul class="list-unstyled">
          <li>
            <p>
              <%= link_to "HOME", root_path, {:style=>"font-size: 1.5em"}%>
            </p>
          </li>
          <li>
            <p>
              <%= link_to "ACHAT", propertys_path, {:style=>"font-size: 1.5em"}%>
            </p>
          </li>
          <li>
            <p>
              <%= link_to "ACTUALITÉ", actualitys_path, {:style=>"font-size: 1.5em"}%>
            </p>
          </li>
          <li>
            <p>
              <%= link_to "CONTACT", contact_path, {:style=>"font-size: 1.5em"}%>
            </p>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

        <!-- Contact details -->
        <h5 class="font-weight-bold text-uppercase mb-4">Adresse</h5>

        <ul class="list-unstyled">
          <li>
            <p style="font-size: 1.45em;"><%= fa_icon "home" %> Marseille, 13000, France</p>
          </li>
          <li>
            <p style="font-size: 1.45em;"><%= fa_icon "envelope" %> immo+@mail.com</p>
          </li>
          <li>
            <p style="font-size: 1.45em;"><%= fa_icon "phone" %> 07.23.12.25.39</p>
          </li>
          <li>
            <p style="font-size: 1.45em;"><%= fa_icon "print" %> + 01 234 567 89</p>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 text-center mx-auto my-4">

        <!-- Social buttons -->
        <h5 class="font-weight-bold text-uppercase mb-4">Nous suivre</h5>

        <!-- Facebook -->
        <a type="button" class="btn-floating btn-fb" id="btnsocial">
         <%= fa_icon "facebook" %>
       </a>
       <!-- Twitter -->
       <a type="button" class="btn-floating btn-tw" id="btnsocial">
        <%= fa_icon "twitter" %>
      </a>
      <!-- Google +-->
      <a type="button" class="btn-floating btn-gplus" id="btnsocial">
        <%= fa_icon "google-plus" %>
      </a>

    </div>
    <!-- Grid column -->
  </div>
  <!-- Grid row -->
</div>
<!-- Footer Links -->
<!-- Copyright -->
<div class="footer-copyright text-center py-3">© 2020 Copyright: immo+</div>
<!-- Copyright -->
</footer>
<!-- Footer -->